=== badinOndrej/Browser_config/badin_ondrej.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Odkaz na github: https://github.com/badinOndrej/Browser_config -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Browser_config">
    <xs:complexType>
      <xs:sequence>
        <!-- Obecne nastaveni -->
        <xs:element name="settings_general">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="isDefaultBrowser"/>
              <xs:element type="lang" name="interfaceLang"/>
              <xs:element name="windowCoords">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:short" name="x"/>
                      <xs:attribute type="xs:short" name="y"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="windowSize">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:short" name="w"/>
                      <xs:attribute type="xs:short" name="h"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="maximized"/>
              <xs:element type="dispOnStart" name="onStart"/>
              <xs:element type="xs:anyURI" name="homepage"/>
              <xs:element type="xs:string" name="default_downloadDir"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Nastaveni zobrazeni stranek -->
        <xs:element name="default_web_appearance">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="default_codepage"/>
              <xs:element name="default_color">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="colorHex" name="bkg"/>
                      <xs:attribute type="colorHex" name="text"/>
                      <xs:attribute type="colorHex" name="link"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="default_font_normal">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="typeface"/>
                      <xs:attribute type="xs:byte" name="size"/>
                      <xs:attribute type="fontStyle" name="style"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="default_font_header">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="typeface"/>
                      <xs:attribute type="xs:byte" name="size"/>
                      <xs:attribute type="xs:string" name="style"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="default_font_link">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="typeface"/>
                      <xs:attribute type="xs:byte" name="size"/>
                      <xs:attribute type="xs:string" name="style"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Nastaveni soukromi a bezpecnosti -->
        <xs:element name="privacy_security">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="embeddings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:boolean" name="javascript"/>
                    <xs:element type="xs:boolean" name="iframe"/>
                    <xs:element type="xs:boolean" name="audio"/>
                    <xs:element type="xs:boolean" name="video"/>
                    <xs:element type="xs:boolean" name="fontface"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="rememberCredentials"/>
              <xs:element type="xs:boolean" name="dangerousWebWarning"/>
              <xs:element name="exceptions">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="exception" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:anyURI" name="site" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="keepHistory"/>
              <xs:element name="eraseHistoryAfter">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="period"/>
                      <xs:attribute type="timeUnit" name="unit"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:boolean" name="doNotTrack"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Instalovane doplnky -->
        <xs:element name="installed_plugins">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="plugin" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:float" name="version"/>
                    <xs:element type="xs:string" name="author"/>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element type="xs:boolean" name="active"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Nastaveni synchronizace s cloudem -->
        <xs:element name="sync_settings">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="synchronize"/>
              <xs:element type="xs:string" name="username"/>
              <xs:element type="xs:string" name="passwordHash"/>
              <xs:element type="xs:boolean" name="synchronizeBookmarks"/>
              <xs:element type="xs:boolean" name="synchronizeHistory"/>
              <xs:element type="xs:boolean" name="synchronizeCredentials"/>
              <xs:element type="xs:boolean" name="synchronizePlugins"/>
              <xs:element type="xs:boolean" name="synchronizeSettings"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Zalozky -->
        <xs:element name="bookmarks">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mark" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="inFolder"/>
                    <xs:element type="xs:anyURI" name="site"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Omezani casove jednotky -->
  <xs:simpleType name="timeUnit">
      <xs:restriction base="xs:string">
          <xs:enumeration value="hour" />
          <xs:enumeration value="day" />
          <xs:enumeration value="week" />
          <xs:enumeration value="month" />
      </xs:restriction>
  </xs:simpleType>
  <!-- Omezeni nastaveni zobrazeni stranky pri startu -->
  <xs:simpleType name="dispOnStart">
      <xs:restriction base="xs:string">
          <xs:enumeration value="showHomePage" />
          <xs:enumeration value="showBlankPage" />
          <xs:enumeration value="showPreviousSession" />
      </xs:restriction>
  </xs:simpleType>
  <!-- Omezeni zadani HTML hex kodu barvy -->
  <xs:simpleType name="colorHex">
      <xs:restriction base="xs:string">
          <xs:pattern value="[#][a-fA-F0-9]{6}"/>
      </xs:restriction>
  </xs:simpleType>
  <!-- Omezeni jazyku rozhrani -->
  <xs:simpleType name="lang">
      <xs:restriction base="xs:string">
          <xs:pattern value="en_GB|en_US|fr_FR|de_DE|it_IT|cs_CZ|pl_PL" />
      </xs:restriction>
  </xs:simpleType>
  <!-- Omezeni stylu rezu pisma -->
  <xs:simpleType name="fontStyle">
      <xs:restriction base="xs:string">
          <xs:pattern value="(normal|bold|underlined|italic)+" />
      </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== badinOndrej/Browser_config/badin_ondrej.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Odkaz na github: https://github.com/badinOndrej/Browser_config -->
<?xml-stylesheet type="text/xsl" href="badin_ondrej.xsl"?>
<!-- Nastaveni weboveho prohlizece -->
<Browser_config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="badin_ondrej.xsd">

<!-- Obecne nastaveni -->
<settings_general>
  <isDefaultBrowser>true</isDefaultBrowser>
  <interfaceLang>cs_CZ</interfaceLang>
  <windowCoords x="140" y="150" />
  <windowSize w="920" h="600" />
  <maximized>true</maximized>
  <onStart>showHomePage</onStart>
  <homepage>http://www.homepage.info</homepage>
  <default_downloadDir>file://C:/Users/karelNovak/Downloads</default_downloadDir>
</settings_general>

<!-- Nastaveni zobrazeni stranek -->
<default_web_appearance>
  <default_codepage>UTF-8</default_codepage>
  <default_color bkg="#ffffff" text="#000000" link="#0000ff" />
  <default_font_normal typeface="Arial" size="10" style="normal" />
  <default_font_header typeface="Arial" size="18" style="bold" />
  <default_font_link typeface="Arial" size="10" style="bold underlined" />
</default_web_appearance>

<!-- Nastaveni soukromi a bezpecnosti -->
<privacy_security>
  <!-- bezpecnost -->
  <embeddings>
    <javascript>false</javascript>
    <iframe>true</iframe>
    <audio>true</audio>
    <video>true</video>
    <fontface>true</fontface>
  </embeddings>
  <rememberCredentials>false</rememberCredentials>
  <dangerousWebWarning>true</dangerousWebWarning>
  <exceptions>
    <exception site="http://www.page1.com" />
    <exception site="http://www.page2.com" />  
  </exceptions>
  <!-- soukromi -->
  <keepHistory>true</keepHistory>
  <eraseHistoryAfter period="30" unit="day" />
  <doNotTrack>true</doNotTrack>
</privacy_security>

<!-- Instalovane doplnky -->
<installed_plugins>
  <plugin>
    <name>AdBlocker</name>
    <version>15.1</version>
    <author>AdBlocker Corp</author>
    <description>Blocks annoying adverts</description>
    <active>true</active>  
  </plugin>
  <plugin>
    <name>Flash Player</name>
    <version>24.0</version>
    <author>Adobe Corporation</author>
    <description>Needed to play SWF animations</description>
    <active>false</active>  
  </plugin>
  <plugin>
    <name>LinkMaker</name>
    <version>2.5</version>
    <author>Juan Juan</author>
    <description>Parses websites for unmarked links and makes them clickable</description>
    <active>true</active>  
  </plugin>
</installed_plugins>

<!-- Nastaveni synchronizace s cloudem -->
<sync_settings>
  <synchronize>true</synchronize>
  <username>karelNovak1</username>
  <passwordHash>8929f11b00a7c0328eb8e0176f3b55a38c1d602e7344f1b0bcc9a7aa1defc074</passwordHash>
  <synchronizeBookmarks>true</synchronizeBookmarks>
  <synchronizeHistory>false</synchronizeHistory>
  <synchronizeCredentials>false</synchronizeCredentials>
  <synchronizePlugins>true</synchronizePlugins>
  <synchronizeSettings>true</synchronizeSettings>
</sync_settings>

<!-- Zalozky -->
<bookmarks>
  <mark>
    <name>Page 1</name>
    <inFolder>$bookmarks</inFolder>
    <site>http://www.page1.com</site>
  </mark>
  <mark>
    <name>Page 2</name>
    <inFolder>$bookmarks/zabava</inFolder>
    <site>http://www.page2.com</site>
  </mark>
  <mark>
    <name>Page 3</name>
    <inFolder>$bookmarks/zabava</inFolder>
    <site>http://www.page3.com</site>
  </mark>
  <mark>
    <name>Page 4</name>
    <inFolder>$bookmarks</inFolder>
    <site>http://www.page4.com</site>
  </mark>
  <mark>
    <name>Page 5</name>
    <inFolder>$bookmarks</inFolder>
    <site>http://www.page5.com</site>
  </mark>
</bookmarks>

</Browser_config>
